### ISSUE TITLE
softmax_classifier()  unexpected keyword  'class_count'

### ISSUE THREAD

**Issue by AloshkaD** [Hvass-Labs/TensorFlow-Tutorials#10]
Hi,

I'm running tf 0.12.0-rc0, CPU on Ubuntu 14.04 64-bit, Python 3.5
My prettytensor is '0.7.1'

I'm runing tutorial 9 and in wrapping the transfer-values as a Pretty Tensor object I get this error

softmax_classifier() got an unexpected keyword argument 'class_count'

I skipped tutorial 3 where prettytensor is introduced  so I didn't run the code there but I would expect the same error with softmax. 
I read issue[ #9](https://github.com/Hvass-Labs/TensorFlow-Tutorials/issues/9) and it pointed out that version mismatch between pt and tf can cause errors but in my case I have the latest of both, to the best of my knowledge. my tf environment is initialized to python 3.5 by default. 

Here is the full error 

```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-97-00471178f1d1> in <module>()
      3 
      4 with pt.defaults_scope(activation_fn=tf.nn.relu):
----> 5     y_pred, loss = x_pretty.        fully_connected(size=1024, name='layer_fc1').        softmax_classifier(class_count=num_classes, labels=y_true)

/home/ros/anaconda3/envs/tf/lib/python3.5/site-packages/prettytensor/pretty_tensor_class.py in method(input_layer, *args, **kwargs)
   2007     @functools.wraps(func)
   2008     def method(input_layer, *args, **kwargs):
-> 2009       return func(input_layer, *args, **self.fill_kwargs(input_layer, kwargs))
   2010 
   2011     return method

TypeError: softmax_classifier() got an unexpected keyword argument 'class_count'```

**Comment by Hvass-Labs** [comment]
Thanks for reporting this. I'm currently transitioning to a new PC so I don't have time to investigate right now. But a quick look shows this:

https://github.com/google/prettytensor/blob/master/prettytensor/pretty_tensor_loss_methods.py#L440-L448

The argument is now named `num_classes` instead of `class_count`. Please try and rename it in the Notebook and see if it works and report back here.

I looked at the change-history of PrettyTensor but it does not mention this keyword. Maybe the reason is that I've installed PT with pip and it was an older version.

Did you also install PT with pip?

**Comment by ibadami** [comment]
If you remove the keyword class_count and just enter the number of classes, it works. 
I do not know the source of the issue but just the fix. In case you are in hurry running the tutorial, this will help. Happy coding!!

**Comment by ibadami** [comment]
I had a similar problem after I installed latest tensorflow 12.0 and pretty tensor 7.0 using pip. 
I changed the `class_count` to `num_classes` and now it works!

**Comment by AloshkaD** [comment]
Awesome, it worked after changing  `class_count` to `num_classes` . Magnus and Ibadami!
btw, I've used pip to install PT but I remember having problems with the installation and I had to redo it several times.
