### ISSUE TITLE
cannot import plot_histogram and plot_objective_2D

### ISSUE THREAD

**Issue by schoon1990** [Hvass-Labs/TensorFlow-Tutorials#100]
Why can't import these from skopt.plots? Also, space.point.to_dict(search_result.x) is giving me an error saying there's no attribute.

**Comment by Hvass-Labs** [comment]
It is clearly stated in the Notebook that some of the plotting functions haven't been merged into the official release of scikit-optimize. I had a conflict with the library's authors and they have refused to merge these improvements into their library. So you should just try and remove the function calls that are causing problems. The Notebook should work without them.
