### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'gfile' in style transfer notebook 

### ISSUE THREAD

**Issue by MianUmair001** [Hvass-Labs/TensorFlow-Tutorials#117]
I am getting this error while running the last cell of this code 
%%time
img = style_transfer(content_image=content_image,
                     style_image=style_image,
                     content_layer_ids=content_layer_ids,
                     style_layer_ids=style_layer_ids,
                     weight_content=1.5,
                     weight_style=10.0,
                     weight_denoise=0.3,
                     num_iterations=60,
                     step_size=10.0)
![15](https://user-images.githubusercontent.com/21352564/70379637-ecd9db80-1950-11ea-8163-22dbf9b067b3.png)

**Comment by m4-k131** [comment]
Use tf.io.gfile.GFile

**Comment by Hvass-Labs** [comment]
Thanks for the error report. I'm guessing this is perhaps part of the TF2 update. Please test the proposed fix and let me know if everything else is working with this Notebook.

**Comment by Hvass-Labs** [comment]
This is a problem within the pre-trained model or some other old TensorFlow code that was used in that tutorial. It would take too much effort to update it to TensorFlow 2, so if you want to run it, you will have to use an older TensorFlow 1 version.
