### ISSUE TITLE
ValueError: could not convert string to float: '28-12-2017'. I am training the time series prediction model on stock market data set and faced this error

### ISSUE THREAD

**Issue by AnimeshMaheshwari22** [Hvass-Labs/TensorFlow-Tutorials#122]
Hello sir. You had added fields of time and date in your weather data set and the code worked. I have the field of date in the data set and facing an error here:

x_train_scaled = x_scaler.fit_transform(x_train)
ValueError: could not convert string to float: '28-12-2017'

**Comment by Hvass-Labs** [comment]
I don't understand. Are you using your own dataset? I cannot give you support for your own dataset. If it is a problem with my code or my dataset, then please write the detailed error-report along with the various software versions you are using for Python, pandas, numpy, TensorFlow, etc.
