### ISSUE TITLE
issue when implementing image caption model

### ISSUE THREAD

**Issue by John-p-v1999** [Hvass-Labs/TensorFlow-Tutorials#125]
I trained the model, following your instructions. But for some reason, the model produces the same caption for different images. It is as if it is ignoring the initial state supplied to the GRU layer. Can you please help me out

**Comment by John-p-v1999** [comment]
actually, the model gives the same caption for every image. Elaborating on my intuition that the model is "ignoring" the initial sate. When I give start_word as another word(instead of 'sos'), different captions are generated. In fact generate captions works fine, the problem is it does not generate according to images. on the contrary caption generation of caption only depends on start word

**Comment by Hvass-Labs** [comment]
I can see this is your first issue on github so I am going to be extremely nice. You cannot expect anyone to help you with a question like this. Look at the date when the tutorial was made - it was YEARS ago! You cannot expect me to remember the details anymore. So I would have to spend hours investigating this problem, and in the end my experience has always been, that it is the user who made problems, so I wasted my time trying to solve non-existent problems. You are coming across as very inconsiderate and selfish when you are posting a question like this. In the future when you post a question on github, stackoverflow, or somewhere else, you need to be very specific about exactly what you have done to the code and data, how you run it, and what the result is. And I would also recommend that you write proper English and capitalize and punctuate your sentences properly. You can't even put a tiny bit of effort into writing a legible question with proper syntax that makes it easy for me to read and maybe answer it, but you expect me to spend hours solving your problems. It really ticks me off when people are being so selfish and inconsiderate.

**Comment by John-p-v1999** [comment]
Pardon my inexperience.

https://api.accredible.com/v1/frontend/credential_website_embed_image/badge/22999930

**Comment by EmperorKonstantin** [comment]
@John-p-v1999 fork this repo and commit your work to your fork, push it to github and link to it or just make a gist and also link it it... @Hvass-Labs wants to see some code, and in general it is good practice to provide your code so you can either be helped along or an actual bug is found and fixed. Or if it's short enough just provide a snippet here surrounded by code tags.
