### ISSUE TITLE
Pretty tensor with tensorboard

### ISSUE THREAD

**Issue by ibadami** [Hvass-Labs/TensorFlow-Tutorials#13]
Sorry for opening an issue for this question. 
Are you planning to add a tutorial for Tensorboard with prettytensor?
I figured how to use tensorboard with low level tensorflow network modelling but still do not understand how I can use it with prettytensor.

**Comment by Hvass-Labs** [comment]
Thanks for the request. Unfortunately I don't think I will be doing a tutorial on that. I would instead suggest that you ask the author of prettytensor to improve the documentation on this subject. If you make a list of specific questions then it is easier for him to answer. Just make a list of everything that confuses you.

**Comment by samadak** [comment]
Hi
Thank you for all your tutorial.
How can i extract feature of an image in Tensorflow?
