### ISSUE TITLE
Tutorial 22_Image_Captioning.ipynb is not working in Colab because of disk space limit

### ISSUE THREAD

**Issue by neuralcomputer** [Hvass-Labs/TensorFlow-Tutorials#130]
Tutorial 22_Image_Captioning.ipynb is not working in Google Colab because of disk space limit. It fails on dataset unzipping line. Colab provide only 68Gb with GPU backend (25-30 already wasted).

Is it possible to provide a trained generator and\or saved transfer-values files to avoid downloading images themselves?

**Comment by Hvass-Labs** [comment]
I think it was maybe 4 years ago that I made that tutorial, so it's a lot to ask for me to do follow-up work on it now. If downloading large files is the problem, then you could try and go to a public library with a good internet connection. You are very welcome to modify the tutorial and make it available to others on your own github account, with the modifications you would prefer.

**Comment by neuralcomputer** [comment]
Thanks for your answer.
Cache files of train and validation transfer-values available at:
- transfer_values_train.pkl (900Mb): https://drive.google.com/file/d/1z-IIMhEccKO6IbEOeWa2QUP37NamYEVb/view?usp=sharing
- transfer_values_val.pkl (40Mb): https://drive.google.com/file/d/1H0XgMkpm1H3Qy5zYAJFByUwoOVc8IY6j/view?usp=sharing
