### ISSUE TITLE
Weird error when calling transfer_values_cache function

### ISSUE THREAD

**Issue by jurastm** [Hvass-Labs/TensorFlow-Tutorials#14]
When I run the script and trying to call this function:
 ```
transfer_values_test = transfer_values_cache(file_path=file_path_cache_test, 
                                              images=images_scaled,
                                              model=model)
```
I face strange errror:

```
OSError                                   Traceback (most recent call last)
<ipython-input-13-d3f5056fe5a9> in <module>()
      9 transfer_values_test = transfer_values_cache(file_path=file_path_cache_test,
     10                                              images=images_scaled,
---> 11                                              model=model)

/Users/mylaptop/TensorFlow-Tutorials-master/inception.py in transfer_values_cache(file_path, images, model)
    553         # Load the transfer-values from the file.
    554         with open(file_path, mode='rb') as file:
--> 555             transfer_values = np.load(file)
    556 
    557         print("- Transfer-values loaded from cache-file.")

/Users/mylaptop/anaconda3/envs/tensorflow/lib/python3.5/site-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    390         N = len(format.MAGIC_PREFIX)
    391         magic = fid.read(N)
--> 392         fid.seek(-N, 1)  # back-up
    393         if magic.startswith(_ZIP_PREFIX):
    394             # zip-file (assume .npz)

OSError: [Errno 22] Invalid argument
```

Does anyone have same issue or any idea how to solve it?
Maybe problem in my numpy library, but still have no idea what exactly is wrong.
My system: OSX El Capitan 10.11.6, Python 3.5 Anaconda

**Comment by Hvass-Labs** [comment]
Thanks for the report. I'm currently in the process of getting a new Linux PC working. It has taken me several days so far because there's a million problems. If you find the solution to your problem in the meantime, then please report it here in case anyone else has the same error in the future.

**Comment by jurastm** [comment]
Found what is the problem. Occasionally I had empty .npy file named same as cache file with transfer values. So, when python tried to download empty file interpreter returned error. 
So, you either have to have normal cache file with transfer values or don't have such filename at all.

Solved.
