### ISSUE TITLE
pretty tensor version?

### ISSUE THREAD

**Issue by apiszcz** [Hvass-Labs/TensorFlow-Tutorials#16]
I'm noting a prettytensor error with 0.7.1. (posted on their issue list), I'm wondering what version of prettytensor you are using? Thank you for the youtube tutorial series and github site.

__version__ = '0.7.1'

    import prettytensor as pt
  File "lib\prettytensor\__init__.py", line 25, in <module>
    from prettytensor import funcs
  File "lib\prettytensor\funcs.py", line 25, in <module>
    from prettytensor.pretty_tensor_image_methods import *
  File "lib\prettytensor\pretty_tensor_image_methods.py", line 135, in <module>
    class conv2d(prettytensor.VarStoreMethod):
  File "lib\prettytensor\pretty_tensor_image_methods.py", line 145, in conv2d
    bias=tf.zeros_initializer(),
TypeError: zeros_initializer() missing 1 required positional argument: 'shape'

**Comment by Hvass-Labs** [comment]
A week ago I tested all tutorials on both GPU and CPU with TensorFlow v. 0.12 and PrettyTensor 0.7.3 and it all worked. However, PrettyTensor did not have the correct __version__ number so it still reports 0.7.1

If you update then hopefully it works again:

    pip install --upgrade prettytensor
