### ISSUE TITLE
Error at protobuf decoding for VGG init. 

### ISSUE THREAD

**Issue by hsucw** [Hvass-Labs/TensorFlow-Tutorials#17]
Hi, 

When I run the tutorial 15, I got the `DecodeError: Truncated message.` The error is due to extract the graph definition from vgg. The data length is not matched with the expected size. It seems fine on Ubuntu. What may cause this problem? Thanks for any reply. 

--
Here is my environment:
OS X Sierra
ipython (5.1.0)
jupyter (1.0.0)
protobuf (3.1.0.post1)
tensorflow (0.12.1)
tensorflow-gpu (0.12.1)
python 3.5.2

The following is the detail.
--
<ipython-input-39-532140502900> in style_transfer(content_image, style_image, content_layer_ids, style_layer_ids, weight_content, weight_style, weight_denoise, num_iterations, step_size)
     27     # operations to the graph so it can grow very large
     28     # and run out of RAM if we keep using the same instance.
---> 29     model = vgg16.VGG16()
     30 
     31     # Create a TensorFlow-session.

/Users/hsucw/Documents/TensorFlow-Tutorials/vgg16.py in __init__(self)
    111 
    112                 # Then we load the proto-buf file into the graph-def.
--> 113                 graph_def.ParseFromString(file.read())
    114 
    115                 # Finally we import the graph-def to the default TensorFlow graph.

/Users/hsucw/anaconda3/envs/tf/lib/python3.5/site-packages/google/protobuf/message.py in ParseFromString(self, serialized)
    183     """
    184     self.Clear()
--> 185     self.MergeFromString(serialized)
    186 
    187   def SerializeToString(self):

/Users/hsucw/anaconda3/envs/tf/lib/python3.5/site-packages/google/protobuf/internal/python_message.py in MergeFromString(self, serialized)
   1085     length = len(serialized)
   1086     try:
-> 1087       if self._InternalParse(serialized, 0, length) != length:
   1088         # The only reason _InternalParse would return early is if it
   1089         # encountered an end-group tag.

/Users/hsucw/anaconda3/envs/tf/lib/python3.5/site-packages/google/protobuf/internal/python_message.py in InternalParse(self, buffer, pos, end)
   1121         pos = new_pos
   1122       else:
-> 1123         pos = field_decoder(buffer, new_pos, end, self, field_dict)
   1124         if field_desc:
   1125           self._UpdateOneofState(field_desc)

/Users/hsucw/anaconda3/envs/tf/lib/python3.5/site-packages/google/protobuf/internal/decoder.py in DecodeRepeatedField(buffer, pos, end, message, field_dict)
    608         new_pos = pos + size
    609         if new_pos > end:
--> 610           raise _DecodeError('Truncated message.')
    611         # Read sub-message.
    612         if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:

DecodeError: Truncated message.

**Comment by Hvass-Labs** [comment]
Thanks for the report. Unfortunately I don't know what might cause this error as I have never seen it. It might be a corrupt file e.g. if the download was aborted midways, but you say it works fine on Ubuntu.

I did a search and found this thread that might be related: https://github.com/tensorflow/tensorflow/issues/3002

Please make a comment here if you find the solution so it may help others in the future.

**Comment by hsucw** [comment]
Solved! It is so simple and stupid.
 Thanks for your reminder about download corrupt data. So I check the md5 of the two vgg models. Apparently, it is not the same value. I remove and download again. Good to go now. Thanks!
