### ISSUE TITLE
how to make convolution neural network for binary features?

### ISSUE THREAD

**Issue by dinasaif** [Hvass-Labs/TensorFlow-Tutorials#18]
I have (ARFF) file or excel file  with binary features (1,0) I want to make CNN for that file.
 I read some resources which wrote about using CNN with image classification but I don't know how can I use it it my classifier?
Thanks

**Comment by Hvass-Labs** [comment]
Please ask this type of question on StackOverflow. It is not an issue that is directly related to these tutorials.
