### ISSUE TITLE
import inception ImportError: No module named request

### ISSUE THREAD

**Issue by Yaffa1607** [Hvass-Labs/TensorFlow-Tutorials#2]
When i try to import inception : i get this error. 
WHen I tried to install requests , I find it here. 
pip install requests
Requirement already satisfied (use --upgrade to upgrade): requests in ./anaconda/lib/python2.7/site-packages

**Comment by Hvass-Labs** [comment]
I'm sorry but I don't really understand your error message. These tutorials don't require a package called 'requests' as far as I know. It also looks like you are using Python 2.7 but these tutorials were developed for Python 3.5 and may not work in Python 2.7. Please see the README for installation instructions.
