### ISSUE TITLE
How can we use our own model with DeepDream example?

### ISSUE THREAD

**Issue by Coderx7** [Hvass-Labs/TensorFlow-Tutorials#20]
I have followed your tutorial so far and noticed deepdream and wanted to give it a try!
I noticed you are using the google's inception pretrained model. 
I wanted to experiment a little bit, so trained a cifar10 model according  to the [tutorial #6](https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/06_CIFAR-10.ipynb), but the checkpoints seem not to be usable with the deepdream tutorial . 
Is it possible for you to add a new tutorial or show in the deepdream tutorial how we can use our own trained models instead of inceptions?

**Comment by Hvass-Labs** [comment]
TensorFlow's checkpoint system is very delicate and if you make tiny changes to the graph for the neural network then it won't load the checkpoint again. But I'm not sure if this is the problem you are having.

Unfortunately I don't have time to make the tutorials you request. I am not employed by Google or some university. I have made all this on my own time for my own money - and it has already taken a long time and been very expensive for me.

Also note that it takes a long time to become fluent with TensorFlow. The only way is to try and solve a lot of problems yourself. Tutorials are just a starting point for your own experiments. That is why I write suggestions for exercises at the end of each tutorial.
