### ISSUE TITLE
Can not run inception.py on Ubuntu 14.04 with Python 2.7

### ISSUE THREAD

**Issue by knodir** [Hvass-Labs/TensorFlow-Tutorials#22]
I get "ImportError: No module named download". See full trace below. I tried "pip install download" and pip does not seem to have a module "download". How do I install it?

$ python inception.py 
Traceback (most recent call last):
  File "inception.py", line 59, in <module>
    import download
ImportError: No module named download

I tried the rest of the code and also get "ImportError: cannot import name cache". See below. 
[...]
Traceback (most recent call last):
  File "inception.py", line 60, in <module>
    from cache import cache
ImportError: cannot import name cache

Can you please point out workaround? Here is my Python version:
$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2

Thanks!

**Comment by Hvass-Labs** [comment]
Two things:

1. The requirements in the README clearly state that it uses Python 3.5 and it might cause problems to use Python 2.7.

2. It looks like you haven't downloaded all the files. This is also discussed in the installation instructions.

If this fixes the problem then please close the issue.

**Comment by knodir** [comment]
Worked. Following your (1) and (2) suggestions solved all problems. Sorry for overlooking the requirements.
