### ISSUE TITLE
Store Trained Model Reference

### ISSUE THREAD

**Issue by Caspain** [Hvass-Labs/TensorFlow-Tutorials#25]
Good day, how exactly can we store the trained model and use it in a  custom API. The way it is currently it will always load a pickled model and train ?

**Comment by Hvass-Labs** [comment]
This is a general question about TensorFlow. Please ask on StackOverflow.

The following message came up before you posted your question, please read it:

https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/.github/ISSUE_TEMPLATE.md
