### ISSUE TITLE
Notebook validation failed for  TensorFlow Tutorial #07

### ISSUE THREAD

**Issue by bochuxt** [Hvass-Labs/TensorFlow-Tutorials#29]
I am reaching issue for 07_
TensorFlow Tutorial #07

Inception Model.

The error is following and I am using python 3.5. Other tutorial notebook works fine.

Notebook validation failed
An invalid notebook may not function properly. The validation error was:

Notebook Validation failed: {'data': {'image/jpeg': ['/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a\nHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy\nMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCABkAGQDA

5dR3Eiwwwyrzbs22/pSqKMDHBU5z1JbcmlQhWOoJWU7GnRmfOc0qVVJujyESOn3Eg3z3qU\nnvZxFjmpUqam9TEBeXDyh1kwysCGUjIIPUGq74t0HT7O0N9axGF2kCmND5N8747fht7UqVSpvcbi\nfQKNYzvSpVUiwzmtlO9KlWOBToFxLIiBmzyPsfwFEkUjAsc7nb6UqVT5PQom/O0nmY74HT4pUqVJ\nGH//2Q==\n'], 'text/plain': ['<IPython.core.display.Image object>']}, 'metadata': {}} is not valid under any of the given schemas:
{
 "data": {
  "image/jpeg": [
   "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a\nHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy\nMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCABkAGQDASIA\nAhEBAxEB/8QAHAAAAQQDAQAAAAAAAAAAAAAABgAEBQcBAgMI/8QANRAAAgEDAgQFAQYGAwEAAAAA\nAQIDAAQRBSEGEjFBEyJRYXGRBzKBobHBFBUjQlLwYtHh8f/EABkBAAMBAQEAAAAAAAAAAAAAAAID\nBAABBf/EAB8RAAICAwEBAAMAAAAAAAAAAAABAhEDEi

U5lXDDpjGaBB0qQ0u8Frc+bPI21LnG0\nZOmWzZ6gIIVYLzSYyBj1p218QlrHy+Zm8SRj27n8tqGLK9Ajj3PNzDv+VSi3DG88oGFjwM9vepZK\nhqZIza5dR3Eiwwwyrzbs22/pSqKMDHBU5z1JbcmlQhWOoJWU7GnRmfOc0qVVJujyESOn3Eg3z3qU\nnvZxFjmpUqam9TEBeXDyh1kwysCGUjIIPUGq74t0HT7O0N9axGF2kCmND5N8747fht7UqVSpvcbi\nfQKNYzvSpVUiwzmtlO9KlWOBToFxLIiBmzyPsfwFEkUjAsc7nb6UqVT5PQom/O0nmY74HT4pUqVJ\nGH//2Q==\n"
  ],
  "text/plain": [
   "<IPython.core.display.Image object>"
  ]
 },
 "metadata": {}
}

-------error from console----
[E 10:20:15.985 NotebookApp] Error while saving file: 07_Inception_Model.ipynb 'output_type'
    Traceback (most recent call last):
      File "/Users/george/venv3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/Users/george/venv3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 430, in check_and_sign
        if self.notary.check_cells(nb):
      File "/Users/george/venv3/lib/python3.6/site-packages/nbformat/sign.py", line 519, in check_cells
        if not self._check_cell(cell, nb.nbformat):
      File "/Users/george/venv3/lib/python3.6/site-packages/nbformat/sign.py", line 496, in _check_cell
        output_type = output['output_type']
    KeyError: 'output_type'
[W 10:20:15.985 NotebookApp] Unexpected error while saving file: 07_Inception_Model.ipynb 'output_type'
[E 10:20:15.986 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "1339391",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|70a7ad28|30d00af3f4023e29207223ff62c8dec7|1490633765",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/07_Inception_Model.ipynb",
      "Accept-Encoding": "gzip, deflate, sdch, br",
      "Accept-Language": "en-US,en;q=0.8",
      "Cookie": "Pycharm-4c29cf31=f471dedd-8846-4455-897d-9c942b1d2dc2; Webstorm-1c198702=45d6dd50-61b4-4e0c-8b92-6f75374fb86a; _xsrf=2|70a7ad28|30d00af3f4023e29207223ff62c8dec7|1490633765; username-localhost-8888=\"2|1:0|10:1491321420|23:username-localhost-8888|44:ZDBkODVkYTk5NzFiNDU3OTk5MjU5MjI1MDRlNTJmOGI=|559c109a5e57333a232ffa931526b7f3169fc576a7bf738aa64ad5f1d61d00d9\""
    }
[E 10:20:15.986 NotebookApp] 500 PUT /api/contents/07_Inception_Model.ipynb (::1) 11.11ms referer=http://localhost:8888/notebooks/07_Inception_Model.ipynb

**Comment by Hvass-Labs** [comment]
I haven't seen this error before. I would have guessed that maybe your download was incomplete / corrupted. But this thread https://github.com/jupyter/notebook/issues/1964 suggests you might have saved the Notebook in another program that has invalidated the file? Please try and re-download the Notebook and see if that fixes it. Please leave a comment here on what solved the problem to help people in the future.

**Comment by Hvass-Labs** [comment]
I'll assume you solved the problem. Please leave a comment on how you solved it, so it may help others in the future.
