### ISSUE TITLE
Classification accuracy of the CIFAR10 model

### ISSUE THREAD

**Issue by sidgan** [Hvass-Labs/TensorFlow-Tutorials#33]
What is the classification accuracy of the CIFAR10 model? When I train the network using tensorflow and GPU's it does not increase beyond 60%. Please confirm if this is the maximum accuracy that this model attained when you were training it.

**Comment by Hvass-Labs** [comment]
I'm assuming you are talking about Tutorial 06. As described in the Notebook, I used a CPU which achieved about 80% accuracy on the test-set after 150k iterations of training. If you find the reason for the difference you are experiencing then please leave a comment here so it may help others in the future.
