### ISSUE TITLE
Style Transfer Question

### ISSUE THREAD

**Issue by dovanchan** [Hvass-Labs/TensorFlow-Tutorials#35]
![image](https://cloud.githubusercontent.com/assets/26133721/25170398/f95fda60-251c-11e7-80aa-0ceb02e94b5c.png)

In this photo from youtube,Can you tell me what parameters you used for generating these result?
I hope I can get a detail answer,Thanks

**Comment by Hvass-Labs** [comment]
In the video I said very clearly that I don't know how to get this good results. However, you could try and disable the automatic normalization of the weights and select the weights yourself. Maybe that will work.
