### ISSUE TITLE
Add your youtube channel to the readme file as well

### ISSUE THREAD

**Issue by Coderx7** [Hvass-Labs/TensorFlow-Tutorials#4]
Hi and Thanks alot for the nice tutorial you created. 
It would be a good idea to also include your youtube channel where you actually teach these tutorials.
Keep up the good job 
Best Regards

**Comment by Coderx7** [comment]
oh, I just noticed you have already done that! 
anyway, good job again!

**Comment by Hvass-Labs** [comment]
The YouTube link is twice in the README and once in every tutorial :-)

But thanks for the compliment!
