### ISSUE TITLE
Import error, cannot import name one_hot_encoder

### ISSUE THREAD

**Issue by NeilNie** [Hvass-Labs/TensorFlow-Tutorials#42]
When I tried to import cifar10.py, this error occurs

```
 ImportError:   Traceback (most recent call last)
<ipython-input-2-4925188f42c0> in <module>()
----> 1 import cifar10

/Users/Neil/Documents/Developer/Machine Learning/Machine Learning with Python/CIFAR-10 Tensorflow/cifar10.py in <module>()
     37 import os
     38 import download
---> 39 from dataset import one_hot_encoded
     40 
     41 ########################################################################

ImportError: cannot import name one_hot_encoded

```

This can resolved by editing the cifar10.py file: replace `from dataset import one_hot_encoded` with `from sklearn.preprocessing import OneHotEncoder`

**Comment by Hvass-Labs** [comment]
Thanks for the suggestion of using the function from sklearn instead. But I have not had this problem before. Are you sure you have downloaded the whole github repo including the file `dataset.py`?

**Comment by NeilNie** [comment]
Thanks for your reply. You are absolutely correct, I realized that there are a couple of files missing in my repo. Now the problem is resolved. I apologize for the misunderstanding.

**Comment by stalin59** [comment]
Could help me, because I have the same mistake

**Comment by Bowenwu1** [comment]
Thank you!
Help me a lot!
