### ISSUE TITLE
AttributeError: 'DataSet' object has no attribute 'cls'

### ISSUE THREAD

**Issue by atinesh** [Hvass-Labs/TensorFlow-Tutorials#47]
Getting an error while reading MNIST data in 
"TensorFlow-Tutorials/02_Convolutional_Neural_Network.ipynb"

```
cls_true = data.test.cls[0:9]
AttributeError: 'DataSet' object has no attribute 'cls'
```

I'm using Tenserflow Version: '1.3.0'

**Comment by kjzhang9** [comment]
did you type `data.test.cls = np.argmax(data.test.labels, axis=1)` before? If not, you can try it. Hope it's helpful to you.

**Comment by atinesh** [comment]
Thanks kjzhang9 it worked

**Comment by sunilsharma07** [comment]
just reference,  Concept is Add a variable to a class instance at runtime .

Thanks
