### ISSUE TITLE
cifar10 training

### ISSUE THREAD

**Issue by ghost** [Hvass-Labs/TensorFlow-Tutorials#48]
i trained my cifar10 based on your notebook file and cifar10.py to read. but batch accuracy only 10% with any cnn architectures and data augmentation or not (with 100000 iterations). do you know what happened? thanks!

**Comment by Hvass-Labs** [comment]
Obviously I cannot know what happened from the 2 lines you wrote here. You can try posting your code on StackOverflow and see if anyone can help you there.
