### ISSUE TITLE
ValueError: Cannot feed value of shape (64, 784) for Tensor 'x_data_2:0', which has shape '(?, 728)'

### ISSUE THREAD

**Issue by Coderx7** [Hvass-Labs/TensorFlow-Tutorials#5]
I tried to create the second tutorial, but I'm failing! this is the code for the whole tutorial 
```
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from tensorflow.examples.tutorials.mnist import input_data

#read data
data = input_data.read_data_sets('data/MNIST/', one_hot=True)

#useful info
image_size =28
img_size_flattened = 728
num_class = 10

#create place holders 
x_data = tf.placeholder(tf.float32,[None,img_size_flattened],name='x_data')

#since our convlayer accepts images in format of [#,imgheight,imgwidths,channels] we need to have a reshaped version as well
x_data_reshaped = tf.reshape(x_data,[-1,image_size,image_size,1],name='x_data_reshape')
y_label_vec = tf.placeholder(tf.float32,[None,num_class],name='y_label_vec')
y_label_true_indx = tf.arg_max(y_label_vec,dimension=1,name='y_label_true_indx')

#create helper methods for conv layer creations
#create methods for creating weights and biases 

def add_weight (shape):
    return tf.Variable(tf.truncated_normal(shape,stddev=0.05))
def add_bias(length):
    return tf.Variable(tf.ones(length))

#returns layer, and weights
def add_conv(input,num_channel,kernel_size,num_kernel,use_pool=True):
    
    shape = [kernel_size,kernel_size,num_channel,num_kernel]
    weights = add_weight(shape)
    biases = add_bias(num_kernel)
    layer = tf.nn.conv2d(input=input,filter=weights,strides=[1,1,1,1],padding='SAME')
    if use_pool:
        layer = tf.nn.max_pool(layer,ksize=[1,2,2,1],strides=[1,2,2,1],padding='SAME')
        
    layer = tf.nn.relu(layer)    
    return layer, weights

#create fc layer, but since we need flattened vectors  to connect to fc, lets create a flatten helper function

#returns layerflattended, and numberoffeatures(volumn length)
def flatten(layer):
    layer_shape = layer.get_shape()
    numberof_features = layer_shape[1:4].num_elements()
    layer_reshaped = tf.reshape(layer, [-1,numberof_features])
    return layer_reshaped,numberof_features
    
#now create helper function for fc 
def add_fc(flattenedlayer,num_input,num_output,Activation=None):
    weights = add_weight([num_input,num_output])
    biases = add_bias(num_output)
    output = tf.matmul(flattenedlayer,weights) + biases
    if Activation != None:
        output = Activation(output)
    return output    

#now lets create layers 
laye_conv1,w1 = add_conv(input=x_data_reshaped, num_channel=1, kernel_size=5, num_kernel=16)
layer_conv2,w2 = add_conv(input=laye_conv1, num_channel=16, kernel_size=5, num_kernel=36)

flat_Layer,num_features = flatten(layer_conv2)

layer_fc1 = add_fc(flattenedlayer=flat_Layer,num_input=num_features,num_output=128, Activation=tf.nn.relu)
layer_fc2 = add_fc(layer_fc1,num_input=128,num_output=10)

#calculate prediction 
pred = tf.nn.softmax(layer_fc2)
pred_labl_true_index = tf.argmax(pred, dimension=1)

#calculate accuracy
correctPredcition = tf.equal(pred_labl_true_index, y_label_true_indx)
accuracy = tf.reduce_mean(tf.cast(correctPredcition,tf.float32))

#crossendtropy
cross_entropy = tf.nn.softmax_cross_entropy_with_logits(layer_fc2,y_label_vec)
loss = tf.reduce_mean(cross_entropy)
train = tf.train.GradientDescentOptimizer(0.2).minimize(loss)

sess = tf.Session()
sess.run(tf.initialize_all_variables())
data.test.true_lbl_indexes = [np.argmax(l) for l in data.test.labels]
for i in range(1000):
    x_dt, x_lbl = data.train.next_batch(100)
    dict = {x_data:x_dt, y_label_vec:x_lbl}
    sess.run(train, feed_dict=dict)
    if i%20 == 0:
        test_dic = {x_data:data.test.images,
                    y_label_vec:data.test.labels,
                    y_label_true_indx: data.test.true_lbl_indexes}
        acc = sess.run(accuracy,feed_dict=test_dic)
        print (acc) 
```
The whole code is based on the exact tutorial codes, but yet it fails! I checked it several times and I have no idea whats causing the error and why!

**Comment by Coderx7** [comment]
oh I got it! 
silly me miscalculated `img_size_flattened = 728 `!

**Comment by tmagg** [comment]
I am trying to run the MNIST code without any error from the below code ( segment 1) , however at the time of restoring the model which is in segment 2 below , i am getting the error as : Cannot feed value of shape (784,) for Tensor 'input:0', which has shape '(?, 784) , kindly suggest

# segment 1
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
import matplotlib.pyplot as plt
from random import randint
import numpy as np

logs_path = 'log_mnist_softmax'
batch_size = 100
learning_rate = 0.5
training_epochs = 10
mnist = input_data.read_data_sets("data", one_hot=True)

X = tf.placeholder(tf.float32, [None, 784], name = "input")
Y_ = tf.placeholder(tf.float32, [None, 10])
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))
XX = tf.reshape(X, [-1, 784])

Y = tf.matmul(X, W) + b
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y_, logits=Y), name = "output")
correct_prediction = tf.equal(tf.argmax(Y, 1), tf.argmax(Y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

train_step = tf.train.GradientDescentOptimizer(0.005).minimize(cross_entropy)

tf.summary.scalar("cost", cross_entropy)
tf.summary.scalar("accuracy", accuracy)
summary_op = tf.summary.merge_all()

with tf.Session() as sess:
sess.run(tf.global_variables_initializer())
writer = tf.summary.FileWriter(logs_path, 
graph=tf.get_default_graph())
for epoch in range(training_epochs):
batch_count = int(mnist.train.num_examples / batch_size)
for i in range(batch_count):
batch_x, batch_y = mnist.train.next_batch(batch_size)
_, summary = sess.run([train_step, summary_op], feed_dict={X: batch_x, Y_: batch_y})
writer.add_summary(summary, epoch * batch_count + i)
print("Epoch: ", epoch)

```
print("Accuracy: ", accuracy.eval(feed_dict={X: mnist.test.images, Y_: mnist.test.labels}))
print("done")

num = randint(0, mnist.test.images.shape[0])
img = mnist.test.images[num]

classification = sess.run(tf.argmax(Y, 1), feed_dict={X: [img]})
print('Neural Network predicted', classification[0])
print('Real label is:', np.argmax(mnist.test.labels[num]))

saver = tf.train.Saver()
save_path = saver.save(sess, "data/saved_mnist_cnn.ckpt")
print("Model saved to %s" % save_path)
```
# Segment 2 for restoring the model

import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets('data', one_hot=True)
sess = tf.InteractiveSession()
new_saver = tf.train.import_meta_graph('data\saved_mnist_cnn.ckpt.meta')
new_saver.restore(sess, 'data\saved_mnist_cnn.ckpt')
tf.get_default_graph().as_graph_def()

x = sess.graph.get_tensor_by_name("input:0")

y_conv = sess.graph.get_tensor_by_name("output:0")
image_b = mnist.test.images[100]
result = sess.run(y_conv, feed_dict={x:image_b})
print(result)
print(sess.run(tf.argmax(result, 1)))

plt.imshow(image_b.reshape([28, 28]), cmap='Greys')
plt.show()
