### ISSUE TITLE
Tensor flow   compile error 

### ISSUE THREAD

**Issue by prabirsinha** [Hvass-Labs/TensorFlow-Tutorials#51]
Hi , 

I am having the following error  in running the CIFAR10 dataset training . Can you give me some where to fix this issue.
"
File "C:\Users\Prabir Sinha\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1001, in concat
    ).assert_is_compatible_with(tensor_shape.scalar())
  File "C:\Users\Prabir Sinha\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 756, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (2, 1) and () are incompatible "

Thanks 
Prabir

**Comment by Hvass-Labs** [comment]
I think this is the first time I've heard about this error. Have you modified the code or perhaps not downloaded everything? Or are you not running the Notebook from the beginning?

You also don't write how this error is connected with the code for the CIFAR10 dataset. These two errors are inside TensorFlow. Please try and debug / make print-statements to find out where in the CIFAR10 code the problem is.

**Comment by prabirsinha** [comment]
Hi,


Let me explain what I did . I had download your tutorial from your url
link  https://github.com/Hvass-Labs/TensorFlow-Tutorials

and follow the steps  shown in
https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/06_CIFAR-10.ipynb
.

Following is my tool setup

>>> tf.__version__
'0.12.0-rc0'
>>> pt.__version__
'0.7.4'

As per your steps I copy all the lines and put into a  file
cifar10_summaries.py inside  the folder where I download your tutorial. Now
from Python IDLE window I source this file with no modification . When I
run this file I encounter this error

"  File "C:\Users\Prabir
Sinha\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\array_ops.py",
line 1003, in concat
    ).assert_is_compatible_with(tensor_shape.scalar())
  File "C:\Users\Prabir
Sinha\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\tensor_shape.py",
line 756, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (2, 1) and () are incompatible "

It may sound strange or weired to you but this is the fact. .

Appreciate if you can help here.

Thanks
Prabir

**Comment by Hvass-Labs** [comment]
You copied the contents of the Notebook into a .py file? Did the Notebook run OK? Perhaps you made a mistake when copying the code?

The two error messages are inside TensorFlow, not in my code. 

"Shapes (2, 1) and () are incompatible" tells you that two tensors have the wrong shapes. The error appears to be a call to `concat` but I did a search and I don't seem to use `concat` anywhere in my code.

Please try and debug this yourself, there is really nothing I can do to help. When you find the solution then please write it here in case others have the same problem in the future.

**Comment by felipeardilac** [comment]
I had the same issue running the 06_CIFAR-10 tutorial, and I fix it updating my tensorflow version to 1.3.0 and now it works

python -m pip uninstall tensorflow
pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.3.0-cp35-cp35m-win_amd64.whl

Also, I had another issue with prettytensor '0.7.4'
TypeError: zeros_initializer() missing 1 required positional argument: 'shape'
and I fix it changing : 
tf.zeros_initializer() to tf.constant_initializer(0.0)
In the files: pretty_tensor_image_methods.py, pretty_tensor_loss_methods.py, pretty_tensor_methods.py and recurrent_networks.py located in the folder  C:\Python35\Lib\site-packages\prettytensor

Hope it works for you

**Comment by prabirsinha** [comment]
Hi felipeardilac,


Thanks for the update . I am able to make it run successfully.

Regards
Prabir
