### ISSUE TITLE
Failed to load checkpoints for Breakout

### ISSUE THREAD

**Issue by walterwang** [Hvass-Labs/TensorFlow-Tutorials#52]
When I try to load the checkpoints in Breakout, I get this error: 
Assign requires shapes of both tensors to match. lhs shape= [1024,4] rhs shape= [1024,6]

and also alot of key errors:

**Comment by Hvass-Labs** [comment]
It is impossible for me to help without more details and the proper error messages.

However, if I am just guessing, then perhaps OpenAI has changed the number of operations the agent may take from 6 to 4.
