### ISSUE TITLE
import cifar10 gives : ImportError: No module named 'cifar10'

### ISSUE THREAD

**Issue by Coderx7** [Hvass-Labs/TensorFlow-Tutorials#6]
When try to run your CIFAR10 demo code, I get 
`ImportError: No module named 'cifar10'`
I searched and even tried 
`from tensorflow.image.cifar10 import cifar10`
but this fails as well and says :
`ImportError: No module named 'tensorflow.image'`
Whats wrong here? is that a typo? 
Should I be creating my own cifar10? 
by the way I'm on version 0.10.0 as well

**Comment by Hvass-Labs** [comment]
It is this file:

https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/cifar10.py

If you install these tutorials using git clone or download the zip-file then the file should be in your directory. Please see the README for installation instructions.

Please close this issue if it fixes the problem.

**Comment by jw447** [comment]
I also got an error when I was running cifar10, it says 'no model named download', which is an error from cifar10.py. Could you please let me know how to fix that?

**Comment by jenishah** [comment]
@jw447 : I am getting the same error. How did you fix this?

**Comment by mingukkang** [comment]
I have same error. "no model named download" and i solve it!!!
problem is  because after you download clone from his(Hvass-Labs) github, you just copy cifar10.py and paste cifar10.py to your path alone. you should paste all py codes in his clone to your path!!
in his clone, many module exists!
because i am not good at writing english, if you have difficult in understanding what i mean, plz feedback me

**Comment by sunlei1203** [comment]
if there is a problem with your path ?
whether the path is 'tensorflow.models.tutorials.image.cifar10'?
if yuor path is right, there is a possibility that your system does not contain the path of cifar10.
you can test it as follows:
#import sys
# print(sys.path)
if this is the reason, you can resolve it by configuration your cifar10 path in your software working environment.
I am not so good in written English, but I think you can basically understand what I mean.

**Comment by sunlei1203** [comment]
if there is a problem with your path ?
whether the path is 'tensorflow.models.tutorials.image.cifar10'?
if your path is right, there is a possibility that your system does not contain the path of cifar10.
you can test it as follows:
import sys
print(sys.path)
if this is the reason, you can resolve it by configuration your cifar10 path in your software working environment.
I am not so good in written English, but I think you can basically understand what I mean.

**Comment by lilshun** [comment]
I've solved this problem. 
Windows cpu version,When i run the 5_3_CNN_CIFAR10 code, 
Its shows  ImportError: No module named 'cifar10_input'
First of all,download this file called models-master(https://github.com/tensorflow/models ) 
Secondly,upzip it in your python workpalce.(use this code :  import os,sys 
                                                                                           pwd = os.getcwd()
                                                                                                       print(pwd)) to find your unzipped path.
Finally,in spyder,add the code to import models-master:
    for example:
             import  sys
             path = 'C:\\Users\\.............\\models-master\\tutorials\\image\\cifar10'
             sys.path.append(path)
Following the original code  :import cifar10,cifar10_input  etc...
and it works!!

**Comment by 17863136957** [comment]
maybe you can try this:from tensorflow.models.image.cifar10 import cifar10,cifar10_input

**Comment by wjb321** [comment]
> maybe you can try this:from tensorflow.models.image.cifar10 import cifar10,cifar10_input

it does't work for this

**Comment by wjb321** [comment]
> I've solved this problem.
> Windows cpu version,When i run the 5_3_CNN_CIFAR10 code,
> Its shows ImportError: No module named 'cifar10_input'
> First of all,download this file called models-master(https://github.com/tensorflow/models )
> Secondly,upzip it in your python workpalce.(use this code : import os,sys
> pwd = os.getcwd()
> print(pwd)) to find your unzipped path.
> Finally,in spyder,add the code to import models-master:
> for example:
> import sys
> path = 'C:\Users\.............\models-master\tutorials\image\cifar10'
> sys.path.append(path)
> Following the original code :import cifar10,cifar10_input etc...
> and it works!!

Hi, I found http://github/tensorflow/models, has no tutorials and image it doesn't work

**Comment by Shreya2k10** [comment]
I am facing the same issue and unable to solve the issue with all the tutorial or even web searh
