### ISSUE TITLE
logits and labels must be same size logits_size 

### ISSUE THREAD

**Issue by ghost** [Hvass-Labs/TensorFlow-Tutorials#60]
hi i used my own dataset for train the model but i have error that i mention below . my dataset has 124 class and lables are 1 to 124 , size is 60*60 gray , batch is 10 and result is : 
lables.eval() --> [  1 101 101 103 103 103 103 100 102   1] -- len(lables.eval()  10
orginal pic size -- > (?, 60, 60, 1)
First convolutional layer  (?, 30, 30, 32)
Second convolutional layer.  (?, 15, 15, 64)
flatten.  (?, 14400)
dense .1  (?, 2048)
dense .2  (?, 124)

error 
`ensorflow.python.framework.errors_impl.InvalidArgumentError: logits and labels must have the same 
  first dimension, got logits shape [40,124] and labels shape [10]`

code
`def model_fn(features, labels, mode, params):
    # Reference to the tensor named "image" in the input-function.
    x = features["image"]

    # The convolutional layers expect 4-rank tensors
    # but x is a 2-rank tensor, so reshape it.
    net = tf.reshape(x, [-1, img_size, img_size, num_channels])

    with tf.Session() as sess:
        print(labels.eval(),' ',len(labels.eval()))
        print(net.get_shape())

    # First convolutional layer.
    net = tf.layers.conv2d(inputs=net, name='layer_conv1',
                           filters=32, kernel_size=3,
                           padding='same', activation=tf.nn.relu)
    net = tf.layers.max_pooling2d(inputs=net, pool_size=2, strides=2)
    with tf.Session() as sess:
            print('First convolutional layer ',net.get_shape())
    # Second convolutional layer.
    net = tf.layers.conv2d(inputs=net, name='layer_conv2',
                           filters=64, kernel_size=3,
                           padding='same', activation=tf.nn.relu)
    net = tf.layers.max_pooling2d(inputs=net, pool_size=2, strides=2)
    with tf.Session() as sess:
        # print(labels.eval())
        print('Second convolutional layer. ',net.get_shape())
    # Flatten to a 2-rank tensor.
    net = tf.contrib.layers.flatten(net)
    # Eventually this should be replaced with:
    # net = tf.layers.flatten(net)
    with tf.Session() as sess:
              print('flatten. ', net.get_shape())
    # First fully-connected / dense layer.
    # This uses the ReLU activation function.
    net = tf.layers.dense(inputs=net, name='layer_fc1',
                          units=2048, activation=tf.nn.relu)
    with tf.Session() as sess:
          print('dense .1 ', net.get_shape())
    # Second fully-connected / dense layer.
    # This is the last layer so it does not use an activation function.
    net = tf.layers.dense(inputs=net, name='layer_fc_2',
                          units=num_classes)
    with tf.Session() as sess:
        print('dense .2 ', net.get_shape())
    # Logits output of the neural network.
    logits = net
    y_pred = tf.nn.softmax(logits=logits)
    y_pred_cls = tf.argmax(y_pred, axis=1)

    if mode == tf.estimator.ModeKeys.PREDICT:
        spec = tf.estimator.EstimatorSpec(mode=mode,
                                          predictions=y_pred_cls)
    else:
        cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=labels,
                                                                       logits=logits)
        loss = tf.reduce_mean(cross_entropy)
        optimizer = tf.train.AdamOptimizer(learning_rate=params["learning_rate"])

        train_op = optimizer.minimize(
            loss=loss, global_step=tf.train.get_global_step())
        metrics = \
            {
                "accuracy": tf.metrics.accuracy(labels, y_pred_cls)
            }

        spec = tf.estimator.EstimatorSpec(
            mode=mode,
            loss=loss,
            train_op=train_op,
            eval_metric_ops=metrics)

    return spec`

**Comment by Hvass-Labs** [comment]
I don't give support when people customize my code. You will have to ask on StackOverflow about your problem. You also don't even say which tutorial it is you have modified. Oh, I guess it is the Estimator tutorial. You may want to try using Keras instead.

**Comment by ghost** [comment]
i didn't customize your code just i print tensors shapes and want to use my own dataset instead of knifey dataset at TFRecords & Dataset API code . my problem cause from lables . the knifey dataset lables are 0,1 but mine is 1 to 124 if you know what the problem is please help . thanks for your all useful tutorial . there are helpful for beginners such as me .

**Comment by Hvass-Labs** [comment]
Using your own data-set counts as customization.

You mean your labels are integers? Then you need to convert them to one-hot encoded labels, or you need to use a sparse-cross-entropy in the loss. Please google these words.

I can't offer support to individuals because it would overload me with work. Please post your code and question on StackOverflow, but you need to be careful and explain it well if you want people to help you.

**Comment by ghost** [comment]
really i appreciate you i will try to do as you said . thanks a lot
