### ISSUE TITLE
Error in Hyper parameter optimization tutorial.

### ISSUE THREAD

**Issue by wasifkhanniaz** [Hvass-Labs/TensorFlow-Tutorials#62]
Hello, 
Thanks for the tutorial. I asked the question in the Youtube comment but not answered yet. Can you look into it, please?
When I run (Line 26, or 27 line of your code); "fitness(x=default_parameters)". It gives an error: TypeError: fitness() got an unexpected keyword argument 'learning_rate' . Any idea how to solve it? 
Thanks

**Comment by Hvass-Labs** [comment]
What version of skopt are you running? Please try and pip install using the line in the Notebook.

Have you modified the Notebook? Please checkout the Notebook again from github.

**Comment by wasifkhanniaz** [comment]
Thanks for the answer. Actually, I’m using Spyder (Anaconda), but I will try this tutorial in notebook now. Thanks again 





On Monday, March 26, 2018, 3:16 PM, Hvass-Labs <notifications@github.com> wrote:


What version of skopt are you running? Please try and pip install using the line in the Notebook.

Have you modified the Notebook? Please checkout the Notebook again from github.

**Comment by Hvass-Labs** [comment]
I'm assuming you found a solution for this. Please write it here so it can help others in the future.

**Comment by wasifkhanniaz** [comment]
I tried in Notebook, but it's not working yet.
