### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by QT85** [Hvass-Labs/TensorFlow-Tutorials#64]
# STOP!

Most of the problems people are having are already described in the [installation instructions](https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/README.md).

You should first make a serious attempt to solve your problem.
If you ask a question that has already been answered elsewhere, or if you do not
give enough details about your problem, then your issue may be closed immediately. 
Please don't waste my time!

## Python 3.5

These tutorials were developed in **Python 3.5** and may give strange errors in Python 2.7

## Missing Files

You need to **download the whole repository**, either using `git clone` or as a zip-file. See the [installation instructions](https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/README.md).

## Questions about TensorFlow

General questions about TensorFlow should either be asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) or the [official TensorFlow repository](https://github.com/tensorflow/tensorflow/issues).

## Suggestions for Changes

The tutorials cannot change too much because it would make the [YouTube videos](https://www.youtube.com/playlist?list=PL9Hr9sNUjfsmEu1ZniY0XpHSzl5uihcXZ) too different from the source-code.

## Requests for New Tutorials

These tutorials were made by a single person on his own time. It took a very long time to
research and produce the tutorials. If a topic is not covered then the best thing is to make
a new tutorial by yourself. All you need is a decent microphone, a screen-grabbing tool, and a
video editor. I used the free version of [DaVinci Resolve](https://www.blackmagicdesign.com/products/davinciresolve).

## Other Issues?

Please carefully read the [installation instructions](https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/README.md) and only open an issue if you are still having problems.

**Comment by QT85** [comment]
Hi, 

I had a dataset and tried to train it. Everything was fine until the run new_model.fit_generator. The Error is: "ValueError: Error when checking target: expected dense_4 to have shape (3,) but got array with shape (4,)". I wonder if i need to convert my image to some required format. 

Thanks

**Comment by Hvass-Labs** [comment]
Your question is rude.

1) How do you expect me to help you when you don't even mention what tutorial this is about?
2) The text that is shown when you post a question, and which you didn't even bother to read, and which is still at the top of your question says the following: *"if you do not
give enough details about your problem, then your issue may be closed immediately.
Please don't waste my time!"*
3) It sounds like you are using your own data-set. I do not provide support for customization of my tutorials. Thousands of people would be asking me questions all the time.
