### ISSUE TITLE
Can you also create a demo/example for Conv3D as well? 

### ISSUE THREAD

**Issue by Coderx7** [Hvass-Labs/TensorFlow-Tutorials#7]
Hi, 
I saw your video data example, and thought that you were going to talk about conv3d /N-D conv. 
But apparently I was wrong. However, I searched for such a demo, but could not find any examples for tensorflow in this regard. 
Would you please do a tutorial on this as well ?
Thank you very much

**Comment by Hvass-Labs** [comment]
Thanks for the request. Unfortunately I don't think I will be doing a tutorial on that topic. Why not make a tutorial yourself?
