### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by 22avinash** [Hvass-Labs/TensorFlow-Tutorials#76]
Can you please upload some tutorial on model pruning using tensorflow?

**Comment by Hvass-Labs** [comment]
You deleted this text before you posted your question:

## Requests for New Tutorials

These tutorials were made by a single person on his own time. It took a very long time to
research and produce the tutorials. If a topic is not covered then the best thing is to make
a new tutorial by yourself. All you need is a decent microphone, a screen-grabbing tool, and a
video editor. I used the free version of [DaVinci Resolve](https://www.blackmagicdesign.com/products/davinciresolve).
