### ISSUE TITLE
UnicoreDecode error while defining text and train datasets

### ISSUE THREAD

**Issue by samirverma14337** [Hvass-Labs/TensorFlow-Tutorials#77]
UnicodeDecodeError                        Traceback (most recent call last) <ipython-input-30-1a795535f2b3> in <module>() ----> 1 x_train_text, y_train = imdb.load_data(train=True)       2 x_test_text, y_test = imdb.load_data(train=False)  ~\Anaconda3\lib\imdb.py in load_data(train)     106      107     # Read all the text-files. --> 108     data_pos = [_read_text_file(path) for path in paths_pos]     109     data_neg = [_read_text_file(path) for path in paths_neg]     110   ~\Anaconda3\lib\imdb.py in <listcomp>(.0)     106      107     # Read all the text-files. --> 108     data_pos = [_read_text_file(path) for path in paths_pos]     109     data_neg = [_read_text_file(path) for path in paths_neg]     110   ~\Anaconda3\lib\imdb.py in _read_text_file(path)      57     with open(path, 'rt') as file:      58         # Read a list of strings. ---> 59         lines = file.readlines()      60       61         # Concatenate to a single string.  ~\Anaconda3\lib\encodings\cp1252.py in decode(self, input, final)      21 class IncrementalDecoder(codecs.IncrementalDecoder):      22     def decode(self, input, final=False): ---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]      24       25 class StreamWriter(Codec,codecs.StreamWriter):  UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 803: character maps to <undefined>

**Comment by Hvass-Labs** [comment]
What am I supposed to do with this?!

You deleted the following text before posting this issue:

> You should first make a serious attempt to solve your problem. If you ask a question that has already been answered elsewhere, or if you do not give enough details about your problem, then your issue may be closed immediately.
