### ISSUE TITLE
ModuleNotFoundError: No module named 'mnist'

### ISSUE THREAD

**Issue by francisalfanta** [Hvass-Labs/TensorFlow-Tutorials#80]
from mnist import MNIST
data = MNIST(data_dir="data/MNIST/")
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-f3175b8855ff> in <module>()
----> 1 from mnist import MNIST
      2 data = MNIST(data_dir="data/MNIST/")

ModuleNotFoundError: No module named 'mnist'

**Comment by Hvass-Labs** [comment]
RTFM!

**Comment by ricardobnjunior** [comment]
How this problem was solved?

**Comment by Hvass-Labs** [comment]
Read the "Downloading" section in the README file. You need to clone the entire repo to get all the necessary files.

**Comment by bobvo23** [comment]
@francisalfanta @ricardobnjunior ri
you have add this snippet of code on top of Hvass Collab's file. It will download some dependencies for the import module:

import os
work_dir = "/content/TensorFlow-Tutorials/"
if os.getcwd() != work_dir:
  !git clone https://github.com/Hvass-Labs/TensorFlow-Tutorials
os.chdir(work_dir)

**Comment by ahx-code** [comment]
@francisalfanta @ricardobnjunior  You need to have "mnist.py", "dataset.py", "download.py", "cache.py" in the same working directory.

For instance: 

<img width="217" alt="screen shot 2019-01-03 at 12 33 52" src="https://user-images.githubusercontent.com/8464220/50631055-0b22a480-0f54-11e9-9049-9a857216fdb6.png">

You can find all the listed python files in the Tensorflow-Master folder, thanks to @Hvass-Labs.
