### ISSUE TITLE
change Python version in installation instructions

### ISSUE THREAD

**Issue by ChrisEt** [Hvass-Labs/TensorFlow-Tutorials#84]
Hi,
I propose to change the following line in the [installation instructions](https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/README.md)
`conda create --name tf python=3`
to 
`conda create --name tf python=3.6`

Reason: At the moment, TensorFlow only support Python 3.5 and 3.6. It can easily happen that someone has Python 3.7 installed, which causes pip to be unable to find and install tensorflow.

**Comment by Hvass-Labs** [comment]
Thanks for the suggestion. I have given it some thought. This is a temporary fix until TensorFlow is built for Python 3.7 and then I would have to change it back again. Then next year when Python 3.8 comes out, I would have the same problem again. If people google the error message they will see the explanation. Maybe I will add a short note to the installation instructions.
