### ISSUE TITLE
checkpoint breakout not specified any link in github repo???

### ISSUE THREAD

**Issue by Shivam2230** [Hvass-Labs/TensorFlow-Tutorials#86]
# STOP!

**Please don't waste my time!**

Most of the problems people are having are already described in the [installation instructions](https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/README.md).

You should first make a serious attempt to solve your problem.
If you ask a question that has already been answered elsewhere, or if you do not
give enough details about your problem, then your issue may be closed immediately. 

## Python 3

These tutorials were developed in **Python 3.5** (and higher) and may give strange errors in Python 2.7

## Missing Files

You need to **download the whole repository**, either using `git clone` or as a zip-file. See the [installation instructions](https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/README.md).

## Questions about TensorFlow

General questions about TensorFlow should either be asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) or the [official TensorFlow repository](https://github.com/tensorflow/tensorflow/issues).

## Modifications

Questions about modifications or how to use these tutorials on your own data-set should also be asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow).

Thousands of people are using these tutorials. It is impossible for me to give individual support for your project.

## Suggestions for Changes

The tutorials cannot change too much because it would make the [YouTube videos](https://www.youtube.com/playlist?list=PL9Hr9sNUjfsmEu1ZniY0XpHSzl5uihcXZ) too different from the source-code.

## Requests for New Tutorials

These tutorials were made by a single person on his own time. It took a very long time to
research and produce the tutorials. If a topic is not covered then the best thing is to make
a new tutorial by yourself. All you need is a decent microphone, a screen-grabbing tool, and a
video editor. I used the free version of [DaVinci Resolve](https://www.blackmagicdesign.com/products/davinciresolve).

## Other Issues?

Please carefully read the [installation instructions](https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/README.md) and only open an issue if you are still having problems.

**Comment by Shivam2230** [comment]
please suggest link,,sir!!

**Comment by Hvass-Labs** [comment]
You seem to be talking about Tutorial 16 on Reinforcement Learning.

The tutorial says the following:

> The original version of this tutorial provided some TensorFlow checkpoints with pre-trained models for download. But due to changes in both TensorFlow and OpenAI Gym, these pre-trained models cannot be loaded anymore so they have been deleted from the web-server. You will therefore have to train your own model further below.

You just have to run the training for an hour or so to see that it works. But you have to run it for several days to achieve good performance.
