### ISSUE TITLE
Value error: expected y to be a list of scalars

### ISSUE THREAD

**Issue by enzolupia** [Hvass-Labs/TensorFlow-Tutorials#87]
Hi. I'm trying to launch the code with a really simple case, just for testing I'm using a single parameter:

hp_dimensions = [dim_learning_rate]
hp_default_parameters = [0.001]

Then I've tried to do this:
 search_result = gp_minimize(func=init_training,
                                dimensions= hp_dimensions,
                                acq_func='EI',  # Expected Improvement.
                                n_calls=20,
                                x0=hp_default_parameters)

but after the first execution when the default parameter is used, this exception is raised:
"ValueError: expected y to be a list of scalars"

I hope not to bother you and not to waste your time.
Thanks for your effort.
Have a good day

**Comment by Hvass-Labs** [comment]
You deleted some text before posting this that clearly states that I don't give support for modifications to my code. There are thousands of users of this project, and it would completely overwhelm me if I had to help individuals with their problems modding my code. Furthermore, you don't even say what tutorial this is and I have to infer that myself. You also don't list the complete code or complete error message. So I'm really not happy about this request.

With that being said, your problem might be that a vector or list of floats is expected. Try with two parameters and see if it works. Even a dummy parameter might work.
