### ISSUE TITLE
cannot import name MNIST

### ISSUE THREAD

**Issue by prasoonjha** [Hvass-Labs/TensorFlow-Tutorials#91]
1 get_ipython().system('pip install mnist')
----> 2 from mnist import MNIST
      3 data = MNIST(data_dir="data/MNIST/")

ImportError: cannot import name 'MNIST'

**Comment by prasoonjha** [comment]
1 get_ipython().system('pip install mnist')
----> 2 from mnist import MNIST
      3 data = MNIST(data_dir="data/MNIST/")

ImportError: cannot import name 'MNIST'

**Comment by prasoonjha** [comment]
@Hvass-Labs could you please help me out with this issue?

**Comment by Hvass-Labs** [comment]
It looks like you are trying to install a pip package named mnist. That is wrong. You need to read the installation instructions.

**Comment by bobvo23** [comment]
you have to clone his github repo instead:

import os
work_dir = "/content/TensorFlow-Tutorials/"
if os.getcwd() != work_dir:
  !git clone https://github.com/Hvass-Labs/TensorFlow-Tutorials
os.chdir(work_dir)
